import React from "react";
import Empresa from "../../components/empresa/empresa";

import ArrowImage from "../../assets/icons/Aback.svg";
import Header from '../../components/header/header';
import BoxText from '../../components/boxText/boxText'
import Title from '../../components/title/title'
import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom";

const CodigoDeConduta = () => {
  return (
    <div>

      <div className="background-lair">

        <div className="blur">
         <Header image={ArrowImage}/>

          <Empresa />
          MENSAGEM DA ADMINISTRAÇÃO
SEJA BEM-VINDO AO CÓDIGO DE CONDUTA E ÉTICA DA LÍDER BRASIL DISTRIBUIDORA!

O Código de Conduta e Ética da Líder Brasil distribuidora não busca apenas definir procedimentos, condutas, valores e vedações àqueles que atuam nesta empresa. Sua pretensão é maior: quer despertar nas pessoas o desejo de ser e agir eticamente, por convicção, e atender aos anseios de todas as partes interessadas, sejam cidadãos e cidadãs, parceiros institucionais e demais organizações que interagem com a Líder Brasil ,para que assim não nos conformemos com o comodismo de sermos somente um boa empresa, e busquemos a excelência de sermos uma empresa excelente.

Este Código é a materialização de um desejo: de transformação! A sua publicação, apenas, não é garantia de um comportamento ético. Para que sua existência faça realmente diferença e sentido, pessoal e institucional, faz-se necessário o envolvimento de todos. Dessa forma, a ciência do que é certo é insuficiente. É preciso criar no indivíduo a vontade de fazer o certo, o compromisso de se vincular aos princípios e às regras. Portanto, assim como na construção do Código, a sua aplicação também é coletiva.

Agir de acordo com o Código de Conduta e Ética é responsabilidade de cada um de nós, por isto é importante conhecê-lo, vivenciá-lo e compartilhá-lo, usando-o no dia a dia como parâmetro e inspiração.

Nossos sinceros agradecimentos a todos que contribuíram com a redação deste Código em infindáveis reuniões e discussões sobre a melhor maneira de definir o caminho a seguir, e levar a empresa ao nível mais elevado, “Não nos conformamos mais em sermos somente bons, o mínimo que podemos é ser excelente”.
Ao lançarmos este novo Código de Conduta e Ética, entendemos que ele não termina nesta versão. Começaremos, novamente, a escrever suas próximas edições com as atualizações e informações que colheremos no dia a dia da empresa com a ajuda dos livros de ocorrências e situações que viram no dia a dia. Com os compromissos que reafirmamos a cada dia, por meio de cada uma de nossas ações seremos excelentes.

Um forte abraço,

A ADMINISTRAÇÃO.

Apresentação
A Líder Brasil distribuidora nesse momento, institui seu primeiro Código de Conduta e Ética, este Código, instrumento que é, sobretudo, um mapa de valores, é um conjunto de grandes diretrizes, um referencial de conduta moral e ética para nortear as ações e decisões de todos os colaboradores, independentemente do nível hierárquico.
MISSÃO, VISÃO E VALORES INSTITUCIONAIS
O conjunto da nossa Missão, Visão e Valores nos guia para a construção do Código de Conduta e Ética:

Nossa Missão:
Prestar serviços de excelência visando o melhor atendimento ao cliente para que com o resultado de nossos esforços possamos crescer como pessoas e empresa.

Nossa Visão:
Ser a melhor empresa no segmento de tecnologia, levando para seus clientes as melhores soluções para seu desenvolvimento profissional.

Nossos Valores:
CLIENTES satisfeitos
Eles são a razão de nossa existência.
PESSOAS respeitadas e comprometidas
São elas que tornam tudo possível.
CONDUTA ética, profissional e transparente
É isso que nos proporciona credibilidade.
MATURIDADE econômica, social e intelectual
É o que nos faz crescer e dá a perspectiva do amanhã.

 

PRINCÍPIOS GERAIS
O Código foi construído com a participação da empresa e de seu consultor o Ceo da empresa e a Gerência. Todas as ações que adotamos no exercício de nossas funções de trabalho devem ser baseados em princípios éticos norteadores, no relacionamento com nossos clientes internos e externos, fornecedores, prestadores de serviços, comunidade, mídia, e demais partes interessadas e relacionadas.


A QUEM O CÓDIGO SE APLICA
As normas deste Código de Conduta e Ética se aplicam aos seus colaboradores: empregados (sem distinção de cargo ou função), aos aprendizes, aos estagiários, aos assessores, aos Administradores (Conselheiros e Diretores), ainda que transitoriamente e sem remuneração, por eleição, nomeação, designação, contratação ou qualquer outra forma de investidura ou vínculo com a Líder Brasil.  Sujeitam-se ainda, no que couberem, os contratados terceirizados e prestadores de serviços.



A LÍDER BRASIL COMPROMETE-SE A:
Cumprir e promover o cumprimento deste Código de Conduta e Ética mediante dispositivos de gestão, divulgando-o permanentemente no intuito de esclarecer dúvidas e acolher sugestões, bem como submeter as suas práticas a processos de avaliação periódica;
Garantir segurança e saúde no trabalho, disponibilizando as condições e equipamentos necessários.  Manter os programas de Saúde e Segurança do Trabalho, visando à higiene ocupacional e prevenção de acidentes e doenças ocupacionais, de forma a proporcionar um local de trabalho seguro e saudável;
Assegurar a disponibilidade e transparência das informações que afetam os seus empregados, preservando os direitos de privacidade no manejo de informações médicas, funcionais e pessoais a eles pertinentes;
Reconhecer o direito de livre associação de seus empregados, respeitar e valorizar sua participação no sindicato e não praticar ou permitir qualquer tipo de discriminação com relação a seus empregados, sindicalizado ou não;
Respeitar e promover a diversidade e combater todas as formas de preconceito e discriminação, por meio de política transparente de admissão, treinamento, promoção na carreira, ascensão a cargos e na aplicação de penalidades. Nenhum colaborador ou potencial colaborador receberá tratamento discriminatório em conseqüência de sua raça, cor de pele, origem étnica, nacionalidade, posição social, idade, religião, gênero, orientação sexual, estética pessoal, condição física, mental ou psíquica, estado civil, opinião, convicção política, ou qualquer outro fator de diferenciação individual;
Promover igualdade de oportunidades para todos os empregados, em todas as políticas, práticas e procedimentos, assegurando a aplicação do princípio da isonomia nas relações de trabalho;
Promover de forma ampla e transparente a divulgação das normas internas da Líder Brasil;
Desenvolver uma cultura organizacional que valoriza o intercâmbio e a disseminação de conhecimentos, promovendo a capacitação contínua de seus empregados através do projeto #EUSOLIDER
Respeitar os Estatutos e os Códigos de Ética que disciplinam e regulamentam a profissão dos seus empregados;
Garantir que recursos humanos e materiais disponíveis, sob sua responsabilidade, sejam aplicados com a máxima eficiência, de forma sustentável, na execução das atividades da Líder Brasil.
 

SÃO DEVERES DOS COLABORADORES:
Observar e respeitar as políticas, regulamentos e procedimentos corporativos, o disposto neste Código de Conduta e Ética e demais normas vigentes;
Ser assíduo e pontual;
Comunicar e justificar ao superior hierárquico os casos de atraso, esquecimentos do crachá e, registro do ponto quando obrigatório;
Portar-se com respeito, correção e presteza de acordo com os bons costumes, enquanto estiver a serviço da Líder Brasil;
Exercer com zelo e dedicação as atribuições do seu cargo/função;
Tratar as pessoas com urbanidade, sem discriminação, seja por cor, etnia, classe social, convicção política, naturalidade, sexo, identidade de gênero, orientação sexual, credo, religião, culto, idade, deficiência, nível de escolaridade, nível hierárquico, origem, porte econômico ou localização geográfica;
Atender ao público em geral, com agilidade, presteza, qualidade, urbanidade e respeito, fornecendo informações claras, precisas e confiáveis, devendo atuar de modo a harmonizar as relações entre o cliente e a Líder Brasil. Durante o atendimento, adotar condutas para:
•	Evitar interrupções por razões alheias ao atendimento;
•	Manter clareza de posições e decoro com vistas a motivar respeito e confiança do cliente em geral;
•	Agir com profissionalismo em situações de conflito, procurando manter o controle emocional;
•	Orientar e encaminhar corretamente o cliente quando o atendimento precisar ser realizado em outro setor;
•	Comunicar imediatamente ao superior hierárquico ou, na sua ausência, à Gerência de Gestão de Pessoas, quando, por doença ou por motivo de força maior, não puder comparecer ao trabalho, salvo em situações em que estiver impossibilitado, desde que devidamente comprovado;
•	Zelar pela aparência e higiene pessoal adequadas ao exercício de sua função, saúde e segurança do trabalho, usando vestuários compatíveis com o ambiente em que atuam:
•	Colaboradores que trabalham em áreas operacionais e atendimento ao público, devem vestir os uniformes concedidos pela empresa, conforme as necessidades do processo e as normas de segurança;
•	Colaboradores que trabalham em áreas administrativas devem usar vestimentas condizentes com o ambiente de trabalho, evitando o uso de vestimentas que possam afetar a imagem profissional e a segurança do funcionário ou que sejam incompatíveis com o ambiente de negócios;
•	Quando o colaborador estiver em atividade externa, representando a Líder Brasil, deverá usar vestimentas de acordo com o grau de formalidade do evento;
•	Observar, cumprir e fazer cumprir as normas de segurança da Líder Brasil, as demais normas vigentes acerca da matéria e melhores práticas de prevenção de acidentes:
•	Usar os Equipamentos de Proteção Individual (EPI) e outros de segurança do trabalho, bem como os uniformes, quando recebidos, de forma a evitar acidentes consigo ou com terceiros;
•	Participar prontamente dos simulados de emergências e exercícios de abandono de prédios, organizados pela Brigada de Emergência ou área de Segurança do Trabalho, observando os procedimentos estabelecidos;
•	Participar prontamente de todas as reuniões designadas pela empresa.
•	
•	Informar ao superior imediato ou à área de Segurança do Trabalho qualquer situação que possa colocar em risco a segurança das pessoas e prejudicar o bom andamento das atividades;
•	Zelar pela sua própria segurança e a de seus colegas;
•	Participar dos treinamentos obrigatórios referentes à segurança no trabalho capacitação profissional, para os quais for convocado;
•	Zelar pela economia de material de forma sustentável, pela conservação do patrimônio da empresa, pela conservação das máquinas, equipamentos e utensílios da Líder Brasil, bem como pelas ferramentas e outros materiais a si confiados, tornando-se diretamente responsável por qualquer extravio, dano ou inutilização, provenientes de descuido, omissão ou negligência, sendo passível de desconto dos valores dos equipamentos extraviados e também demissão por justa causa dependendo do caso
•	Assegurar o uso adequado do patrimônio material da empresa, bem como veículos, computadores, ou qualquer outra ferramenta disponibilizada pela empresa, atendendo ao seu legítimo propósito, inclusive para preservar a imagem e reputação da empresa e não utilizá-lo para obter qualquer tipo de vantagem ou uso pessoal;
•	Acatar e cumprir com presteza as ordens e instruções recebidas de seus superiores hierárquicos, cumprindo-as de maneira que possa obter maior rendimento e eficiência, exceto quando manifestadamente ilegais, quando não guardarem relação com as atribuições do cargo ou função, quando desrespeitarem o Código de Ética de cada profissão e cargo exercido, as normas internas da empresa e demais legislações vigentes;
•	Zelar pela limpeza e higiene do local de trabalho e demais dependências da Líder Brasil;
•	Utilizar o crachá, em local visível e de fácil identificação, quando estiver nos estabelecimentos, a serviço, ou representando a Líder Brasil;
•	Respeitar o sigilo profissional, exceto quando autorizado ou exigido por lei;
•	Proteger e assegurar o sigilo das informações e documentos mantidos e divulgados internamente, inclusive técnicas de trabalho e fornecedores, e garantir que não possam ser acessados por pessoas não autorizadas;
•	Prestar todas as informações necessárias, em tempo, com qualidade, confiabilidade e veracidade para o bom andamento do trabalho na Líder Brasil;
•	Dar-se por impedido e/ou suspeito de exercer suas funções nos trabalhos que tenham relação direta com cônjuge, parente consangüíneo ou afim, em linha reta ou colateral até o 3º grau, amigos, inimigos ou pessoas de suas relações, que possam configurar conflito de interesses e em situações que possam violar o Código de Ética de cada profissão ou cargo exercido;
•	Respeitar e proteger a propriedade intelectual da Líder Brasil sobre produtos, processos, pesquisas, estudos, marcas, patentes, fornecedores, processos, inclusive em todas as fases do processo de desenvolvimento de trabalho e implantação;
•	Utilizar os recursos de comunicação e tecnologia da informação somente para as atividades inerentes às atividades profissionais e com observância das normas internas da Líder Brasil;
•	Preservar a integridade de documentos, registros, cadastros, carteira de clientes e sistemas de informação da Líder Brasil, em todos os meios utilizados pela empresa, tanto físico quanto eletrônico;
•	Combater a corrupção em todas as suas formas, inclusive furto , e denunciar os casos a que tiver conhecimento.
 

SÃO CONDUTAS PROIBIDAS AOS COLABORADORES:
Ausentar-se do serviço durante o expediente, sem prévia autorização do superior hierárquico;
Permanecer no local de trabalho fora do horário de expediente, sem prévia autorização do superior hierárquico;
Retirar, sem prévio consentimento da autoridade competente, qualquer documento ou objeto da Líder Brasil;
Coagir ou aliciar pessoas no sentido de filiarem-se à associação profissional, sindical ou a partido político;
Portar armas, apresentar-se em serviço alcoolizado ou sob o efeito do uso de substâncias entorpecentes durante o expediente, nas dependências ou a serviço da Líder Brasil, comprometendo sua integridade física/ moral e/ou do grupo, o desenvolvimento das atividades, a segurança e a imagem da Líder Brasil;
Agir de forma a provocar constrangimento para si ou para outros, praticar atos e gestos obscenos, algazarras, gritaria e o uso de palavras de baixo calão durante o expediente e/ou enquanto estiver a serviço e/ou representando a Líder Brasil;
Proceder de forma desidiosa;
Utilizar pessoal, recursos materiais, maquinários, equipamentos, veículos e/ou ferramentas da Líder Brasil para fins particulares;
Desrespeitar e/ou desacatar os superiores hierárquicos, descumprir ou negligenciar o cumprimento de suas ordens, salvo quando manifestamente ilegais;
Registrar o inicio dos trabalhos no relógio de ponto antes do horário de expediente da empresa, salvo em casos especiais determinados pela direção e gerencia da empresa;
Registrar ponto de outro empregado sob qualquer circunstância e/ou usar as justificativas e ferramentas virtuais de controle de ponto pessoal de má-fé;
Fumar nas dependências da Líder Brasil, exceto em locais preestabelecidos (fumódromos);e no horário de pausa.
Envolver-se em qualquer atividade ou situação que configure conflito de interesse; devendo-se comunicar aos superiores hierárquicos ou aos Canais de Denúncia disponíveis, qualquer situação que configure aparente ou potencial conflito de interesse;
Praticar atos lesivos à empresa, como usurpação, fraude ou quaisquer outros atos ilícitos ou ilegais, como exigir, insinuar, prometer, aceitar ou oferecer qualquer tipo de favor, vantagem, benefício, bem móvel ou imóvel, dinheiro, patrocínio, doação, gratificação, presente, viagem, hospedagem, refeição, de forma direta ou indireta, para influenciar em ação ou decisão, para si ou para qualquer outra pessoa;
Aceitar presentes, brindes, cortesias, ou qualquer tipo de vantagem de clientes, fornecedores e terceiros, exceto quando de caráter promocional e sem valor comercial, como por exemplo: canetas, calendários, agendas, camisetas, com a logo da empresa; os demais deverão ser recusados ou devolvidos, formalmente; na impossibilidade, deverão ser encaminhados ao Comitê de Ética da empresa que determinará a destinação dos mesmos;
Praticar ou ser conivente com atos de preconceito, constrangimento, discriminação, ameaça, chantagem, falso testemunho, assédio moral, assédio sexual ou qualquer outro ato contrário aos princípios e normas vigentes, aos compromissos deste Código e às demais normas da Líder Brasil, denunciando imediatamente os transgressores;
Utilizar de forma inadequada os recursos de tecnologia de informação:
•	Utilizar os recursos de tecnologia de informação com finalidade ilegal ou que possa causar danos à reputação da Líder Brasil;
•	Transmitir ou armazenar informações ameaçadoras, obscenas, perturbadoras, preconceituosas, imorais ou que possam, de alguma forma, caluniar ou difamar a Líder Brasil, seus colaboradores, consultores, terceiros ou parceiros de negócios;
•	Utilizar o correio eletrônico corporativo para fazer propaganda de produtos, serviços ou qualquer atividade de interesse pessoal, em benefício próprio, de outras pessoas ou organizações, enviar ou retransmitir “correntes” de mensagens;
•	Transmitir e/ou instalar programas de computador que violem direitos autorais, a legislação vigente e as normas de TI;
•	Transmitir deliberadamente códigos maliciosos (que podem obter informações sem autorização do usuário) ou vírus de computador;
•	Compartilhar com outras pessoas as senhas de acesso aos sistemas ou às redes internas da Líder Brasil, ou ainda violar a privacidade de outros usuários;
•	Armazenar arquivos pessoais no computador/tablet ou celular da empresa, como por exemplo: músicas, vídeos, livros virtuais, documentos etc., que comprometam a capacidade de armazenamento;
•	Usar os equipamentos fotocopiadores para finalidade de impressões e cópias particulares;
•	Divulgar ou fazer uso de informação privilegiada ou não autorizada, independentemente do seu grau de sigilo, obtida em razão do cargo ou função, em proveito próprio ou de terceiro;
•	Alterar o conteúdo de qualquer documento, informação ou dados, utilizá-lo indevidamente ou sem autorização da chefia;
•	Eliminar documentos em desacordo com as normas de preservação dos mesmos e tabelas de temporalidade;
•	Liberar credita ou cadastro de clientes sem o devido procedimento e processos da empresa.
•	Ser conivente com irregularidades ou infração a este Código ou ao Código de Conduta Ética de seu cargo junto a empresa;
•	Apropriar-se de ideias e/ou méritos relativos aos trabalhos desenvolvidos por outras pessoas, independentemente de sua posição hierárquica;
•	Exercer o comércio particular durante o horário de expediente.
 

MEDIDAS DISCIPLINARES POR VIOLAÇÃO AO CÓDIGO
Este Código é de cumprimento obrigatório. Por isso, é importante que todos saibam que condutas contrárias podem levar à aplicação de medidas disciplinares, que incluem o término da relação de trabalho, sem prejuízo das responsabilizações legais cabíveis.

Este Código não esgota todas as possíveis questões éticas relacionadas ao trabalho e, por isso, não restringe a Líder Brasil na aplicação de medidas disciplinares, que serão sempre orientadas pelo bom senso e legislação aplicável.

São sanções aplicáveis como medidas disciplinares:

Advertência;
Suspensão;
Demissão.
Na aplicação das penalidades, a Líder Brasil observará o princípio da proporcionalidade, a natureza e a gravidade da falta cometida, os danos que dela provierem para o serviço, às circunstâncias atenuantes e agravantes e os antecedentes funcionais.

A advertência será aplicada verbalmente ou por escrito nos casos que não justifique imposição de penalidade mais grave.

A suspensão será aplicada em caso de reincidência das faltas punidas com advertência, ou logo após o cometimento de uma falta que não justifique a aplicação de advertência ou demissão, não podendo exceder 30 (trinta) dias corridos.




A demissão será aplicada nos seguintes casos:

•	Ato de improbidade;
•	Incontinência de conduta ou mau procedimento;
•	Negociação habitual por conta própria ou alheia sem permissão do empregador trazendo de forma direta e indiretamente prejuízo a empresa, e quando constituir ato de concorrência à empresa para a qual trabalha o empregado, ou for prejudicial ao serviço;
•	Condenação criminal do empregado, transitada em julgado, caso não tenha havido suspensão da execução da pena; ou seu recolhimento ao sistema prisional impossibilite seu comparecimento habitual ao trabalho;
•	Desídia no desempenho das respectivas funções;
•	Embriaguez habitual ou em serviço;
•	Violação de segredo da empresa, como fornecedores, dados de clientes, processos de trabalho, rotas de entrega e qualquer outra informação que coloque em risco as operações da empresa;
•	Ato de indisciplina ou de insubordinação;
•	Abandono de emprego;
•	Ato lesivo da honra ou da boa fama praticado no serviço contra qualquer pessoa, ou ofensas físicas, salvo em caso de legítima defesa, própria ou de outrem;
•	Prática constante de jogos de azar;
•	Prática de crime contra a empresa, clientes e colaboradores;
•	Insuficiência de desempenho;
•	A aplicação de demissão, seja por justa causa ou sem justa causa, somente ocorrerá mediante motivação suficiente e adequada do ato de dispensa, razão pela qual o contrato de trabalho somente poderá ser declarado rompido por força de ato administrativo motivado, com justificação relevante, ressalvados os casos dos prestadores de serviços e terceirizados, os quais são de livre nomeação e contrato a parte da CLT.

A Líder Brasil, no exercício do poder disciplinar, após analisar o caso concreto e levar em consideração a gravidade do ato praticado e as conseqüências para o serviço, poderá enquadrar os atos faltosos em outras condutas não tipificadas neste Código de Conduta e Ética.





DILEMAS ÉTICOS
Todos nós estamos sujeitos a passar por dilemas éticos e controversos em nossa trajetória. Antes de decidir se uma conduta ou atividade é apropriada, verifique se o fato ou a decisão:

Está de acordo com a legislação?
Está de acordo com este Código, a Política e demais norma interna da Líder Brasil?
Está de acordo com meus valores pessoais e os valores da Líder Brasil?
Se a resposta a qualquer uma das perguntas acima for negativa, o comportamento ou atividade em questão é inadequado.

Adicionalmente, pergunte a si mesmo se você: teria orgulho de contar aos seus amigos e sua família sobre sua atitude, de vê-la publicada em jornais, ou ainda, se prejudicasse ou colocasse alguém em risco?

Não devemos nos omitir quando nos deparamos com estas situações de dúvida. Responder a estas perguntas ajudará na escolha da melhor conduta nestes casos ou a reconhecer que há uma violação do Código, que precisa ser comunicada.

 

CANAIS DE DENÚNCIAS
Ao vivenciar, testemunhar ou tomar conhecimento de conduta que configure descumprimento às orientações deste Código de Conduta e Ética, deve-se comunicar ou denunciar o fato aos superiores hierárquicos e/ou aos Canais de Denúncias.

Canais disponibilizados para acolher denúncias internas e externas relativas ao descumprimento do Código de Conduta e Ética:

A Líder Brasil respeita e acolhe a comunicação ou denúncia de desvio de conduta feita de boa-fé, e não admite retaliações à pessoa que utilize os canais de denúncias.
 
INSTÂNCIAS INTERNAS RESPONSÁVEIS PELA ATUALIZAÇÃO E APLICAÇÃO DO CÓDIGO DE CONDUTA E ÉTICA

Compete à Presidência da empresa designar Comitê revisor multidisciplinar responsável pela atualização do Código de Conduta e Ética da Líder Brasil.

A aplicação do Código será realizada pelo Comitê de Ética que terá poderes delegados pelo Diretor Presidente para:

•	Assegurar  a  compreensão dos  valores  e  princípios  do  Código,  elucidando  dúvidas  e respondendo consultas;
•	Promover  a  divulgação  do  Código,  inclusive  por meio  de  treinamentos  e campanhas;
•	Receber  denúncias  de  violação,  relatando-as,  analisando-as  e  concluindo  se  houve  conduta antiética ou violação de princípios ou normas;
•	Dar andamento às ações cabíveis para casos de irregularidades ou infrações a este Código ou demais procedimentos vigentes.
 

TREINAMENTO ANUAL
O Código de Conduta e Ética deve estar inserido na programação de treinamentos da Líder Brasil, devendo ser realizado por ocasião do ingresso ou admissão e, periodicamente (no mínimo anual) aos empregados, administradores e demais colaboradores, e, no que couber, aos terceiros.

 







GLOSSÁRIO
 

Atos Lesivos ao código de conduta:
O QUE É ?
 Assédio Moral
Toda e qualquer conduta abusiva e repetitiva, manifestada sobretudo por comportamentos, palavras, atos, gestos e escritos que possam trazer dano à personalidade, à dignidade ou à integridade física ou psíquica de uma pessoa, pondo em perigo seu emprego ou degradando o ambiente de trabalho.
Assédio Sexual
Constrangimento a alguém com o intuito de obter vantagem ou favorecimento sexual, prevalecendo-se o agente de sua condição de superior hierárquico ou de ascendência inerentes ao exercício de emprego, cargo ou função (Código Penal – Artigo 216-A)
Conflito de Interesses

Toda situação em que o empregado, demais colaboradores e administradores, assim como seus parentes ou amigos, possam beneficiar-se do vínculo com a Líder Brasil para obter vantagem pessoal ou em benefício de terceiros de forma conflitante com algum interesse da Líder Brasil.
É a situação gerada pelo confronto entre interesses públicos e privada, que possa comprometer o interesse coletivo ou influenciar, de maneira imprópria, o desempenho da empresa, como por exemplo:

– Divulgar ou fazer uso de informação privilegiada, em proveito próprio ou de terceiro, obtida em razão das atividades exercidas;

– Exercer atividade que implique a prestação de serviços ou a manutenção de relação de negócio com pessoa física ou jurídica que tenha interesse em informações sigilosas da empresa.

– Exercer, direta ou indiretamente, atividade que em razão da sua natureza seja incompatível com as atribuições do cargo ou emprego;

– Praticar ato em benefício de interesse de pessoa física ou jurídica em que se tenha relacionamento como, seu cônjuge, companheiro ou parentes, consangüíneos ou afins, em linha reta ou colateral, até o terceiro grau, e que possa ser por ele beneficiada ou influir em seus atos de gestão trazendo qualquer tipo de prejuízo a empresa, sendo esse financeiro ou administrativo;
– Desenvolver atividades de interesse particular no ambiente de trabalho, usando ou não recursos da empresa. 
Corrupção
Utilização abusiva de uma para ganho pessoal, direta ou indireta. É o abuso do poder em troca de benefícios privados, em razão do que se transgride a lei ou 
Desídia: 
É o tipo de falta grave que, na maioria das vezes, consiste na repetição de pequenas faltas leves, que se vão acumulando até culminar na dispensa do empregado. Isto não quer dizer que uma só falta não possa configurar desídia. Os elementos caracterizadores são a prática habitual de atos que infringem o bom andamento das tarefas a serem executadas durante sua jornada de trabalho. São elementos materiais, ainda, a pouca produção, os atrasos freqüentes, as faltas injustificadas ao serviço, imperfeições na execução do trabalho, abandono do local de trabalho durante a sua jornada, e outros fatos que prejudicam a empresa e demonstram o desinteresse do empregado pelas suas funções.
Informações Privilegiadas
São as informações a que se teve acesso ou conhecimento em função das atribuições do cargo ou função; devem ser preservadas em sigilo de acordo com as determinações da empresa.
Informações Confidenciais ou sigilosas
São as que dizem respeito a assuntos sigilosos ou aquele relevante ao processo de decisão da Líder Brasil, que tenha repercussão econômica ou financeira e que não seja de amplo conhecimento público.
Assim, é vedado disponibilizar, por qualquer meio ou atividade, informações que beneficiem particulares, pessoas jurídicas, clientes e concorrentes, em detrimento do interesse da empresa, permitam a burla aos controles exercidos pela administração ou coloquem em risco a imagem da Líder Brasil.
Entre elas, mas não limitadas a estas, as seguintes: as de natureza comercial (por exemplo, clientes, fornecedores); as de natureza técnica (por exemplo, métodos, know-how, processos, projetos , protegidos ou não por direitos de propriedade industrial ou intelectual); as de natureza estratégica (por exemplo, estratégias futuras de desenvolvimento de negócios, de vendas ou de marketing); aquelas de natureza pessoal (por exemplo, dados cadastrais de empregados, autônomos, clientes, terceirizadas, prestadores de serviços, etc.).
Urbanidade: Cordialidade, cortesia, delicadeza, gentileza ou civilidade.
TERMO DE COMPROMISSO E ADESÃO
A assinatura do Termo de Compromisso anexo a este Código de Conduta e Ética é obrigatória e reflete a expressão do conhecimento do seu conteúdo e a concordância com o cumprimento de suas regras.

ANEXO – TERMO DE COMPROMISSO

Declaro que recebi o Código de Conduta e Ética atualizado da LÍDER BRASIL DISTRIBUIDORA, compreendo os padrões que se aplicam ao meu trabalho e concordo em cumprir seus termos, bem como estou ciente de que o não cumprimento poderá implicar ações disciplinares. Aceito a responsabilidade de estimular a boa conduta ética no ambiente de trabalho e manter uma comunicação aberta com os outros, em relação a questões de práticas de conduta.

A prática do Código de Conduta e Ética é tão importante que cada empregado deve ter seu próprio exemplar, para ler e consultar sempre que preciso.

Este Termo de Compromisso, assinado por mim, passa a ser parte integrante da minha pasta funcional.

Nome:	
Matrícula:	
Cargo/Função:	
Data:	
Assinatura:	
– – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – – –





ANEXO – TERMO DE COMPROMISSO
Declaro que recebi o Código de Conduta e Ética atualizado da LÍDER BRASIL DISTRIBUIDORA, compreendo os padrões que se aplicam ao meu trabalho e concordo em cumprir seus termos, bem como estou ciente de que o não cumprimento poderá implicar ações disciplinares. Aceito a responsabilidade de estimular a boa conduta ética no ambiente de trabalho e manter uma comunicação aberta com os outros, em relação a questões de práticas de conduta.

A prática do Código de Conduta e Ética é tão importante que cada empregado deve ter seu próprio exemplar, para ler e consultar sempre que preciso.

Este Termo de Compromisso, assinado por mim, passa a ser parte integrante da minha pasta funcional.

          <BoxText/>
        </div>
      </div>
    </div>
  );
};

export default CodigoDeConduta;
